[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/cci-metropole-de-bourgogne/"
to = "/organisations/cci-metropole-de-bourgogne/"

[[redirects]]
from = "/atis/"
to = "/organisations/atis/"

[[redirects]]
from = "/ingenierie-gouvernance/"
to = "/cooperation-territoriale/ingenierie-gouvernance/"

[[redirects]]
from = "/cooperation-territoriale-1/"
to = "/cooperation-territoriale/"

[[redirects]]
from = "/adi-nouvelle-aquitaine/"
to = "/organisations/adi-nouvelle-aquitaine/"

[[redirects]]
from = "/communaute-dagglomeration-pays-basque/"
to = "/organisations/communaute-dagglomeration-pays-basque/"

[[redirects]]
from = "/sytec/"
to = "/organisations/sytec/"

[[redirects]]
from = "/la-maison-pour-rebondir/"
to = "/organisations/la-maison-pour-rebondir/"

[[redirects]]
from = "/crdla-transformation-ecologique/"
to = "/organisations/crdla-transformation-ecologique/"

[[redirects]]
from = "/ademe-centre-val-de-loire/"
to = "/organisations/ademe-centre-val-de-loire/"

[[redirects]]
from = "/region-occitanie/"
to = "/organisations/region-occitanie/"

[[redirects]]
from = "/innovation-publique/design-d-innovation-publique-territoriale/"
to = "/innovation-publique/design-innovation/"

[[redirects]]
from = "/cooperation-territoriale-1/ingenierie-gouvernance/"
to = "/cooperation-territoriale/ingenierie-gouvernance/"

[[redirects]]
from = "/programme-rte/"
to = "/organisations/programme-rte/"

[[redirects]]
from = "/soltena/"
to = "/organisations/soltena/"

[[redirects]]
from = "/region-nouvelle-aquitaine/"
to = "/organisations/region-nouvelle-aquitaine/"

[[redirects]]
from = "/irts/"
to = "/organisations/irts/"

[[redirects]]
from = "/cnfpt/"
to = "/organisations/cnfpt/"

[[redirects]]
from = "/cohda/"
to = "/organisations/cohda/"

[[redirects]]
from = "/bordeaux-metropole/"
to = "/organisations/bordeaux-metropole/"

[[redirects]]
from = "/cooperation-territoriale-1/ingenierie-gouvernance-1/"
to = "/cooperation-territoriale/strategie-territoriale/"

[[redirects]]
from = "/qui-sommes-nous/"
to = "/notre-eco-systeme/"

[[redirects]]
from = "/organisations/communaute-dagglomeration-de-pau/"
to = "/organisations/pau-agglomeration/"

[[redirects]]
from = "/bordeaux-sciences-agro/"
to = "/organisations/bordeaux-sciences-agro/"

[[redirects]]
from = "/crij-nouvelle-aquitaine/"
to = "/organisations/crij-nouvelle-aquitaine/"

[[redirects]]
from = "/syndicat-mixte-detudes-et-damenagement-de-la-garonne/"
to = "/organisations/syndicat-mixte-detudes-et-damenagement-de-la-garonne/"

[[redirects]]
from = "/innovation-publique-1/etudes-et-recherche/"
to = "/innovation-publique/etudes-et-enquetes/"

[[redirects]]
from = "/notre-eco-systeme-cooperatif/"
to = "/notre-eco-systeme/"

[[redirects]]
from = "/solutions-locales/robustesse-des-operateurs-des-transitions/"
to = "/solutions-locales/robustesse-operateurs/"

[[redirects]]
from = "/innovation-publique-1/design-d-innovation-publique-territoriale/"
to = "/innovation-publique/design-innovation/"

[[redirects]]
from = "/grand-angouleme/"
to = "/organisations/grand-angouleme/"

[[redirects]]
from = "/rocher-de-palmer/"
to = "/organisations/rocher-de-palmer/"

[[redirects]]
from = "/lets-food/"
to = "/organisations/lets-food/"

[[redirects]]
from = "/cress-nouvelle-aquitaine/"
to = "/organisations/cress-nouvelle-aquitaine/"

[[redirects]]
from = "/nous/"
to = "/nous-contacter/"

[[redirects]]
from = "/atmo/"
to = "/organisations/atmo/"

[[redirects]]
from = "/le-campement/"
to = "/organisations/le-campement/"

[[redirects]]
from = "/pole-territorial-sud-gironde/"
to = "/organisations/pole-territorial-sud-gironde/"

[[redirects]]
from = "/narrau/"
to = "/organisations/narrau/"

[[redirects]]
from = "/cooperation-territoriale/ingenierie-gouvernance-1/"
to = "/cooperation-territoriale/strategie-territoriale/"

[[redirects]]
from = "/mie-anabase/"
to = "/organisations/mie-anabase/"

[[redirects]]
from = "/amnyos/"
to = "/organisations/amnyos/"

[[redirects]]
from = "/jeunesse-habitat-solidaire/"
to = "/organisations/jeunesse-habitat-solidaire/"

[[redirects]]
from = "/grand-figeac/"
to = "/organisations/grand-figeac/"

[[redirects]]
from = "/pole-dinterpretation-de-la-prehistoire/"
to = "/organisations/pole-dinterpretation-de-la-prehistoire/"

[[redirects]]
from = "/guillaume-foucher/"
to = "/personnes/guillaume-foucher/"

[[redirects]]
from = "/la-manuco/"
to = "/organisations/la-manuco/"

[[redirects]]
from = "/organisations/centre-regional-info-jeunesse/"
to = "/organisations/crij-nouvelle-aquitaine/"

[[redirects]]
from = "/communaute-de-communes-caux-austreberthe/"
to = "/organisations/communaute-de-communes-caux-austreberthe/"

[[redirects]]
from = "/organisations/centre-national-de-la-fonction-publique-territoriale/"
to = "/organisations/cnfpt/"

[[redirects]]
from = "/solagro/"
to = "/organisations/solagro/"

[[redirects]]
from = "/innovation-publique-1/innovation-publique-2/"
to = "/innovation-publique/design-innovation/"

[[redirects]]
from = "/universite-de-bordeaux/"
to = "/organisations/universite-de-bordeaux/"

[[redirects]]
from = "/epidor/"
to = "/organisations/epidor/"

[[redirects]]
from = "/astredhor-sud-ouest/"
to = "/organisations/astredhor-sud-ouest/"

[[redirects]]
from = "/udaf/"
to = "/organisations/udaf/"

[[redirects]]
from = "/ville-de-bordeaux/"
to = "/organisations/ville-de-bordeaux/"

[[redirects]]
from = "/alec-bordeaux-gironde/"
to = "/organisations/alec-bordeaux-gironde/"

[[redirects]]
from = "/o-tempora/"
to = "/organisations/o-tempora/"

[[redirects]]
from = "/territoires/"
to = "/cooperation-territoriale/"

[[redirects]]
from = "/delphine-vandevoorde/"
to = "/personnes/delphine-vandevoorde/"

[[redirects]]
from = "/democratie-ouverte/"
to = "/organisations/democratie-ouverte/"

[[redirects]]
from = "/emilie-peytavin/"
to = "/personnes/emilie-peytavin/"

[[redirects]]
from = "/caisse-depargne/"
to = "/organisations/caisse-depargne/"

[[redirects]]
from = "/aract-nouvelle-aquitaine/"
to = "/organisations/aract-nouvelle-aquitaine/"

[[redirects]]
from = "/vrac/"
to = "/organisations/vrac/"

[[redirects]]
from = "/melanie-thuillier/"
to = "/personnes/melanie-thuillier/"

[[redirects]]
from = "/unat-de-bretagne/"
to = "/organisations/unat-de-bretagne/"

[[redirects]]
from = "/ofb/"
to = "/organisations/ofb/"

[[redirects]]
from = "/amg/"
to = "/organisations/amg/"

[[redirects]]
from = "/les-premieres-nouvelle-aquitaine/"
to = "/organisations/les-premieres-nouvelle-aquitaine/"

[[redirects]]
from = "/cooperation-territoriale/facilitation-territoriale/"
to = "/cooperation-territoriale/strategie-territoriale/"

[[redirects]]
from = "/cooperation-territoriale-1/ingenierie-gouvernance-1-1/"
to = "/cooperation-territoriale/ludification/"

[[redirects]]
from = "/grand-poitiers/"
to = "/organisations/grand-poitiers/"

[[redirects]]
from = "/ifaid/"
to = "/organisations/ifaid/"

[[redirects]]
from = "/grand-chatellerault/"
to = "/organisations/grand-chatellerault/"

[[redirects]]
from = "/pluricite/"
to = "/organisations/pluricite/"

[[redirects]]
from = "/innovation-publique-1/evaluation-1/"
to = "/cooperation-territoriale/ingenierie-gouvernance/"

[[redirects]]
from = "/la-traverse/"
to = "/organisations/la-traverse/"

[[redirects]]
from = "/collectif-acclimataction/"
to = "/organisations/collectif-acclimataction/"

[[redirects]]
from = "/la-ruche/"
to = "/organisations/la-ruche/"

[[redirects]]
from = "/cen-nouvelle-aquitaine/"
to = "/organisations/cen-nouvelle-aquitaine/"

[[redirects]]
from = "/lalternative-urbaine/"
to = "/organisations/lalternative-urbaine/"

[[redirects]]
from = "/organisations/institut-regional-du-travail-social-nouvelle-aquitaine/"
to = "/organisations/irts/"

[[redirects]]
from = "/inae-nouvelle-aquitaine/"
to = "/organisations/inae-nouvelle-aquitaine/"

[[redirects]]
from = "/renaud-pousse/"
to = "/personnes/renaud-pousse/"

[[redirects]]
from = "/dla-nouvelle-aquitaine/"
to = "/organisations/dla-nouvelle-aquitaine/"

[[redirects]]
from = "/innovation-publique-1/evaluation/"
to = "/innovation-publique/evaluation/"

[[redirects]]
from = "/anais-trousselle/"
to = "/personnes/anais-trousselle/"

[[redirects]]
from = "/cooperation-territoriale/facilitation-territoriale-et-animation-de-concertations/"
to = "/cooperation-territoriale/strategie-territoriale/"

[[redirects]]
from = "/rennes-metropole/"
to = "/organisations/rennes-metropole/"

[[redirects]]
from = "/cooperation-territoriale-1-1/"
to = "/solutions-locales/"

[[redirects]]
from = "/grenoble-alpes-metropole/"
to = "/organisations/grenoble-alpes-metropole/"

[[redirects]]
from = "/reseau-des-independants-de-la-musique/"
to = "/organisations/reseau-des-independants-de-la-musique/"

[[redirects]]
from = "/sostat/"
to = "/organisations/sostat/"

[[redirects]]
from = "/commune-de-saint-louis-de-montferrand/"
to = "/organisations/commune-de-saint-louis-de-montferrand/"

[[redirects]]
from = "/solutions-locales/transition-ess-1/"
to = "/solutions-locales/robustesse-operateurs/"

[[redirects]]
from = "/etudes-et-enquetes/"
to = "/innovation-publique/etudes-et-enquetes/"

[[redirects]]
from = "/rte/"
to = "/solutions-locales/responsabilite-territoriale/"

[[redirects]]
from = "/sciences-po-bordeaux/"
to = "/organisations/sciences-po-bordeaux/"

[[redirects]]
from = "/organisations/chambre-regionale-de-less-nouvelle-aquitaine/"
to = "/organisations/cress-nouvelle-aquitaine/"

[[redirects]]
from = "/cooperation-territoriale-1/ingenierie-gouvernance-2/"
to = "/cooperation-territoriale/ludification/"

[[redirects]]
from = "/cooperation-territoriale-1-1/transition-ess-1/"
to = "/solutions-locales/robustesse-operateurs/"

[[redirects]]
from = "/pau-agglomeration/"
to = "/organisations/pau-agglomeration/"

[[redirects]]
from = "/cooperation-territoriale-1-1/transition-ess-1-1/"
to = "/solutions-locales/responsabilite-territoriale/"

[[redirects]]
from = "/solutions-locales/transition-ess/"
to = "/solutions-locales/transformation-ess/"

[[redirects]]
from = "/urscop/"
to = "/organisations/urscop/"

[[redirects]]
from = "/departement-de-la-gironde/"
to = "/organisations/departement-de-la-gironde/"

[[redirects]]
from = "/union-saint-jean/"
to = "/organisations/union-saint-jean/"

[[redirects]]
from = "/cress-auvergne-rhone-alpes/"
to = "/organisations/cress-auvergne-rhone-alpes/"

[[redirects]]
from = "/solutions-locales/transition-ess-1-1/"
to = "/solutions-locales/responsabilite-territoriale/"

[[redirects]]
from = "/cooperation-territoriale-1-1/transition-ess/"
to = "/solutions-locales/transformation-ess/"

[[redirects]]
from = "/sophie-humbert/"
to = "/personnes/sophie-humbert/"

[[redirects]]
from = "/uniformation/"
to = "/organisations/uniformation/"

[[redirects]]
from = "/reseau-grape/"
to = "/organisations/reseau-grape/"

[[redirects]]
from = "/pait-grand-region-grenobloise/"
to = "/organisations/pait-grand-region-grenobloise/"

[[redirects]]
from = "/innovation-publique-1/"
to = "/innovation-publique/"

[[redirects]]
from = "/sage-garonne/"
to = "/organisations/sage-garonne/"

[[redirects]]
from = "/sud-ouest-formation-recherche/"
to = "/organisations/sud-ouest-formation-recherche/"

[[redirects]]
from = "/benoit-pous/"
to = "/personnes/benoit-pous/"

[[redirects]]
from = "/felix-associes/"
to = "/organisations/felix-associes/"

